package com.test.sd
import com.test.bean.Message
dialect  "mvel"

// rule  只是执行顺序

rule "Hello World"
    dialect "mvel"
    salience 0
    when
        m : Message(status.equals(Message.HELLO), message : message )
    then
        System.out.println( message);
    modify ( m ) { message = "Goodbye cruel world!!!",status = Message.GOODBYE };
end

rule "Good Bye"
    dialect "java"
    salience 99
    when
       Message( status == Message.GOODBYE, message : message )
    then
        System.out.println( "this is good bye" );
end


rule "test"
 when
  then
    System.out.println("test!!!!");

   end